apiVersion: v1
kind: Pod
metadata:
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - command:
    - kube-apiserver
    - --etcd-servers=http://127.0.0.1:2379
    - --service-cluster-ip-range=10.96.0.0/12
    - --service-account-issuer=ki
    - --api-audiences=ki
    - --tls-cert-file=/etc/kubernetes/pki/api.pem
    - --tls-private-key-file=/etc/kubernetes/pki/api-key.pem
    - --client-ca-file=/etc/kubernetes/pki/ca.pem
    - --service-account-key-file=/etc/kubernetes/pki/sa.pem
    - --service-account-signing-key-file=/etc/kubernetes/pki/sa-key.pem
    - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
    - --kubelet-client-certificate=/etc/kubernetes/pki/admin.pem
    - --kubelet-client-key=/etc/kubernetes/pki/admin-key.pem
    - --authorization-mode=Node,RBAC
    - --enable-bootstrap-token-auth=true
    image: k8s.gcr.io/kube-apiserver:v1.23.1
    name: kube-apiserver
    volumeMounts:
    - mountPath: /etc/kubernetes/pki
      name: pki
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /var/lib/kubelet/pki
      type: DirectoryOrCreate
    name: pki

