apiVersion: v1
kind: Pod
metadata:
  name: init
  namespace: kube-node-lease
spec:
  containers:
  - image: emilyls/kubeadm:v1
    args:
    - init
    - --config=/etc/kubeadm.yaml
    - --skip-phases=preflight
    name: kubeadm
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s-config
    - mountPath: /var/lib/kubelet
      name: kubelet-config
    - mountPath: /etc/kubeadm.yaml
      name: kubeadm-config
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
  # We need this so that kubeadm can work pre CNI setup, and also so
  # that it can correctly see the IP address that the kube-apiserver
  # will be listening on
  hostNetwork: true
  priorityClassName: system-cluster-critical
  restartPolicy: OnFailure
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: k8s-config
  - hostPath:
      path: /var/lib/kubelet
      type: DirectoryOrCreate
    name: kubelet-config
  - hostPath:
      path: /static/kubeadm.yaml
      type: File
    name: kubeadm-config
