apiVersion: v1
kind: Pod
metadata:
  name: dhcpd
spec:
  containers:
  - image: emilyls/dhcp:v1
    imagePullPolicy: Always
    name: busybox
    volumeMounts:
    - mountPath: /etc
      name: config
    # Currently we require running as root but this may change
    securityContext:
      allowPrivilegeEscalation: false
    env:
    - name: INTERFACE
      value: eth0
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc
      type: Directory
    name: config
