apiVersion: v1
kind: Pod
metadata:
  name: dhcpd
  namespace: kube-node-lease
spec:
  containers:
  - image: emilyls/dhcp:v1
    name: busybox
    volumeMounts:
    - mountPath: /etc
      name: config
    # Currently we require running as root but this may change
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
        add:
        - NET_ADMIN
        - NET_RAW
    env:
    - name: INTERFACE
      value: eth0
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc
      type: Directory
    name: config
