site_name: "kiOS: The Kubernetes OS"
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - navigation.indexes
    - navigation.sections
  palette:
    primary: red
    accent: red
  icon:
    logo: fontawesome/solid/ship

copyright: Copyright &copy; 2021 - 2023 Emily Shepherd
repo_url: https://github.com/EmilyShepherd/kiOS
repo_name: kiOS

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


nav:
  - Overview:
    - index.md
    - versioning.md
    - distributions.md
    - license.md
  - Setup:
    - Quick Start:
      - setup/quick-start/index.md
      - Bare Metal:
        - setup/quick-start/bare-metal/location.md
        - setup/quick-start/bare-metal/node-configuration.md
        - setup/quick-start/bare-metal/static-pods.md
      - AWS:
        - setup/quick-start/aws/index.md
        - setup/quick-start/aws/migrate-from-eks.md
        - setup/quick-start/aws/new-cluster.md
    - Hardening kiOS:
      - setup/hardening/image-signing.md
      - setup/hardening/seccomp.md
  - Reference:
    - reference/logs.md
    - Technical:
      - technical/datapart.md
      - technical/files.md

