#!/bin/busybox sh
#
#
BB=/bin/busybox
currenthostname=$($BB cat /proc/sys/kernel/hostname)
hostinterface=$($BB cat /run/dhcp/interface)

# The dhcp client is only designed to obtain the host IP address (if you
# want to use extra networking, run a seperate dhcp client in a pod on
# the host network). If the "host" device has changed (which can happen
# if CNI has bridged with the physical port), then we will switch over
# to that interface.
if [ -n "$interface" ] && [ -n "$hostinterface" ] && [ "$hostinterface" != "$interface" ]
then
  kill $($BB cat /run/dhcp/pid)
fi

case $1 in
  bound|renew)
    # If the DHCP server has given us a hostname, and we don't have one
    # already, then humbly accept it.
    if [ -n "$hostname" ] && [ -z "$currenthostname" ]
    then
      $BB echo $hostname > /proc/sys/kernel/hostname
    fi

    [ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"
    [ -n "$subnet" ] && NETMASK="netmask $subnet"

    $BB ifconfig $interface $ip $BROADCAST $NETMASK

    if [ -n "$router" ]; then
      while $BB iproute del default dev $interface; do :; done

      metric=0
      for i in $router; do
        $BB iproute add default via $i dev $interface metric $metric
        metric=$(($metric + 1))
      done
    fi

    # Update resolver configuration file
    $BB echo "" > /etc/resolv.conf
    [ -n "$domain" ] && /bin/busybox echo "domain $domain" >> /etc/resolv.conf

    for i in $dns; do
      $BB echo "nameserver $i" >> /etc/resolv.conf
    done
  ;;

  deconfig)
    $BB ifconfig $interface 0.0.0.0
  ;;

  leasefail)
    $BB echo "$0: Lease failed: $message"
  ;;

  nak)
    $BB echo "$0: Received a NAK: $message"
  ;;

  init)
    [ -n "$currenthostname" ] && hostname="-F $currenthostname"
    [ -n "$hostinterface" ] && hostinterface="-i $hostinterface"
    $BB mkdir -p /run/dhcp
    exec $BB udhcpc -fs $0 $hostname $hostinterface -p /run/dhcp/pid
  ;;

  *)
    $BB echo "$0: Unknown udhcpc command: $1";
    exit 1;
  ;;
esac
