FROM docker.io/emilyls/musl:1.2.3

COPY /bin/dhcp-cni-init /init
COPY /default.conflist /etc/cni/net.d/
COPY /bin/dhcp /bin/bridge /opt/cni/bin

ENTRYPOINT ["/opt/cni/bin/dhcp", "daemon", "-hostprefix", "host"]

