apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
enableServer: true
staticPodPath: /etc/kubelet/static/
authentication:
  x509:
    clientCAFile: /var/lib/kubelet/pki/ca.pem
  anonymous:
    enabled: false
