#!/bin/sh

if test "$container" != "podman"
then
  exec podman run -it -w/app -v$(pwd):/app alpine scripts/build-all
fi

apk add --no-cache \
  make \
  autoconf \
  automake \
  bison \
  flex \
  bash \
  gcc \
  meson \
  ninja \
  rsync \
  elfutils-dev \
  openssl openssl-dev \
  diffutils \
  git \
  gettext \
  pkgconfig \
  gperf \
  tar \
  curl \
  patch \
  findutils \
  libtool

curl -L https://go.dev/dl/go1.24.5.linux-amd64.tar.gz | tar xzf - -C /
cp /go/bin/go /bin/

export GOROOT=/go
mkdir -p /usr/include

(
  ./scripts/build-pkg.sh lib/musl
  cd pkgs/lib/musl/src
  make install-headers
  cp -r include/* /usr/include/
  cp -r lib/* /lib/
)

(
  cd pkgs/kernel/src
  make headers
  cp -r usr/include/* /usr/include/
)

./scripts/build-pkg.sh lib/libseccomp
./scripts/build-pkg.sh lib/glib

for dir in $(ls pkgs/bin)
do
  ./scripts/build-pkg.sh bin/$dir
done

./scripts/build-pkg.sh kernel
