#!/bin/bash
#
# Pre-downloads images to the given location
#
# This is intended to be used to prime containers within a datapart or
# initramfs so that they can be used before networking is setup.
#
# The images to download can either be given explicitly on the command
# line, or one or more manifest directories can be specified. Any images
# specified in the manifests will be pulled.
#

declare -A images

add_image() {
  local image=$1

  # Docker.io has some weird non standard behaviour which most container
  # tools silently take care of. When an image just has a name and no
  # organisation, it is silently re-rewritten to include "library" as
  # the organisation. We need to be aware of this and do that transform
  # so when we check if an image is needed we correctly identify an
  # image.
  if echo -n $image | grep -sq '^docker\.io/[^/]\+$'
  then
    image=$(echo -n $image | sed 's#/#/library/#')
  fi

  images[$image]="y"
}

while ! test -z "$1"
do
  case "$1" in
    "--root" | "-r")
      ROOT="$2"
      shift
      ;;
    "--manifest-dir" | "-m")
      for img in $(grep image: $2/*.yaml | grep -o '\("[^"]\+"\)\|\([^ "]\+$\)' | sed 's/"//g')
      do
        add_image $img
      done
      shift
      ;;
    "--pause" | "-p")
      add_image "registry.k8s.io/pause:$2"
      shift
      ;;
    *)
      add_image $1
      ;;
  esac
  shift
done

podman="podman --root ${ROOT}"

is_desired() {
  for name in $@
  do
    if test -n "${images[$name]}"
    then
      images[$name]="seen"
      return 0
    fi
  done

  return 1
}

for image in $($podman images --format '{{printf "%s," .Id}}{{- range $i := .Names}}{{printf "%s," $i}}{{- end}}')
do
  if ! is_desired $(echo -n $image | cut -f2- -d, | tr ',' ' ')
  then
    $podman rmi -f $(echo -n $image | cut -f1 -d,)
  fi
done

for image in "${!images[@]}"
do
  if test "${images[$image]}" != "seen"
  then
    $podman pull --platform=linux/amd64 "$image"
  fi
done

cd "${ROOT}"

rm -rf \
  overlay-containers \
  libpod \
  overlay-layers/*.gz \
  volumes \
  defaultNetworkBackend networks \
  *.lock */*.lock db.sql
