#!/bin/busybox sh
#
PATH=/bin
BB=$PATH/busybox

_mount() {
  local dir=$1
  shift
  $BB mkdir -p "$dir"
  $BB mount "$@" "$dir"
}

_mount /proc -o nosuid,noexec,nodev -t proc proc
_mount / -o remount,rw
_mount /sys -o nosuid,noexec,nodev -t sysfs sys
_mount /run -o mode=0755,nosuid,nodev -t tmpfs run
_mount /dev -o mode=0755,nosuid -t devtmpfs dev
_mount /dev/pts -o mode=0620,gid=5,nosuid,noexec -n -t devpts devpts
_mount /dev/shm -o mode=1777,nosuid,nodev -n -t tmpfs shm
_mount /dev/kernel/security -n -t securityfs securityfs
_mount /sys/fs/cgroup -t cgroup2 -o nsdelegate cgroup2

$BB ip link set dev lo up
$BB ip link set dev eth0 up

