apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  chrony.conf: |
    {{- range $pool := .Values.config.pools }}
    pool {{ $pool }}
    {{- end -}}

    {{- range $server := .Values.config.servers }}
    pool {{ $server }}
    {{- end -}}

    {{- if .Values.server.enabled }}
    port {{ .Values.server.containerPort }}
    {{- end -}}

    {{ .Values.config.extraConfig | nindent 4 }}
