{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.server.port }}
      targetPort: ntp
      protocol: UDP
      name: ntp
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
{{- end }}
