FROM alpine:latest as build

WORKDIR /app
RUN apk add --no-cache make gcc libcap libc-dev

COPY src /app

ENV LDFLAGS="-w -s -flto -static"
ENV CFLAGS="-flto"

RUN ./configure --without-libcap
RUN make chronyd
RUN setcap cap_sys_time=+ep chronyd

FROM scratch

COPY --from=build --chown=999:999 /app/chronyd /bin/
COPY --chown=999:999 files/etc /etc

USER 999:999

ENTRYPOINT ["/bin/chronyd", "-Ud"]
CMD ["-6"]
