ARG TARGETPLATFORM

FROM --platform=$BUILDPLATFORM k8s.gcr.io/build-image/setcap:bullseye-v1.0.0

ADD /sbin/chronyd /bin/chronyd
RUN setcap cap_sys_time=+ep /bin/chronyd
RUN echo $TARGETPLATFORM

FROM --platform=${TARGETPLATFORM} docker.io/emilyls/musl:1.2.3

COPY --from=0 --chown=999:999 /bin/chronyd /bin/
COPY /etc/chrony.conf /etc/chrony.conf
COPY /etc/passwd /etc/group /etc/

USER 999:999

ENTRYPOINT ["/bin/chronyd", "-Ud"]
CMD ["-6"]
