FROM docker.io/squidfunk/mkdocs-material AS builder

COPY mkdocs.yml /docs/
COPY docs /docs/docs

RUN mkdocs build

FROM docker.io/nginxinc/nginx-unprivileged:alpine

# Can't believe IPv6 isn't on by default.
RUN sed -i 's/8080/\[::\]:8080/' /etc/nginx/conf.d/default.conf

COPY --from=builder /docs/site /usr/share/nginx/html/
