apiVersion: v1
kind: Pod
metadata:
  name: resize-disk
  namespace: kube-node-lease
spec:
  restartPolicy: Never
  initContainers:
  - image: emilyls/parted:v2
    name: parted
    securityContext:
      # Required to allow parted to open the block device
      privileged: true
    args:
    - "-sf"
    - /dev/nvme0n1
    - resizepart
    - "2"
    - "100%"
  containers:
  - image: emilyls/resize2fs:v1
    name: resize2fs
    securityContext:
      # Required to allow resize2fs to open the block device
      privileged: true
    args:
    - /dev/nvme0n1p2
