apiVersion: v1
kind: Pod
metadata:
  name: init
  namespace: kube-node-lease
spec:
  containers:
  - image: emilyls/bootstrap:v1
    args:
    - /run/config
    name: init
    volumeMounts:
    - mountPath: /etc/kubernetes
      name: k8s-config
    - mountPath: /var/lib/kubelet
      name: kubelet-config
    - mountPath: /run/config
      name: config
      readOnly: true
    - mountPath: /etc/resolv.conf
      name: resolv
    - mountPath: /etc/hostname
      name: hostname
    - mountPath: /tmp
      name: tmp
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - SYS_ADMIN
  # We need this so that kubeadm can work pre CNI setup, and also so
  # that it can correctly see the IP address that the kube-apiserver
  # will be listening on
  hostNetwork: true
  priorityClassName: system-cluster-critical
  restartPolicy: OnFailure
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes
      type: DirectoryOrCreate
    name: k8s-config
  - hostPath:
      path: /var/lib/kubelet
      type: DirectoryOrCreate
    name: kubelet-config
  - hostPath:
      path: /tmp/bootpart/init.toml
      type: File
    name: config
  - hostPath:
      path: /etc/resolv.conf
      type: FileOrCreate
    name: resolv
  - hostPath:
      path: /etc/hostname
      type: FileOrCreate
    name: hostname
  - emptyDir: {}
    name: tmp
