#ifndef _DHCP_CNI_H
#define _DHCP_CNI_H 1

const char *DHCP_CNI_MANIFEST =
"apiVersion: v1\n"
"kind: Pod\n"
"metadata:\n"
"  name: dhcpd-%s-%s\n"
"  namespace: kube-node-lease\n"
"spec:\n"
"  initContainers:\n"
"  - image: emilyls/dhcp-cni:v1\n"
"    name: dhcp-install\n"
"    args:\n"
"    - init\n"
"    env:\n"
"    - name: BRIDGE_WITH\n"
"      value: %s\n"
"    - name: BRIDGE\n"
"      value: %s\n"
"    volumeMounts:\n"
"    - mountPath: /host/opt/cni/bin\n"
"      name: cni-bin\n"
"    - mountPath: /host/etc/cni/net.d\n"
"      name: cni-etc\n"
"    securityContext:\n"
"      allowPrivilegeEscalation: false\n"
"      capabilities:\n"
"        drop:\n"
"        - ALL\n"
"        add:\n"
"        - NET_ADMIN\n"
"  containers:\n"
"  - image: emilyls/dhcp-cni:v1\n"
"    name: dhcp-ipam\n"
"    volumeMounts:\n"
"    - mountPath: /host/run\n"
"      name: run\n"
"    - mountPath: /host/var/run/netns\n"
"      name: netns\n"
"      mountPropagation: HostToContainer\n"
"    securityContext:\n"
"      allowPrivilegeEscalation: false\n"
"      capabilities:\n"
"        drop:\n"
"        - ALL\n"
"        add:\n"
"        - NET_ADMIN\n"
"        - NET_RAW\n"
"        # Required for setns\n"
"        - SYS_ADMIN\n"
"  - image: emilyls/dhcp:v1\n"
"    name: dhcp-host\n"
"    securityContext:\n"
"      allowPrivilegeEscalation: false\n"
"      capabilities:\n"
"        drop:\n"
"        - ALL\n"
"        add:\n"
"        - NET_ADMIN\n"
"        - NET_RAW\n"
"    volumeMounts:\n"
"    - mountPath: /etc\n"
"      name: host-etc\n"
"    env:\n"
"    - name: INTERFACE\n"
"      value: %s\n"
"  hostNetwork: true\n"
"  priorityClassName: system-node-critical\n"
"  tolerations:\n"
"  - operator: Exists\n"
"  volumes:\n"
"  - hostPath:\n"
"      path: /opt/cni/bin\n"
"      type: DirectoryOrCreate\n"
"    name: cni-bin\n"
"  - hostPath:\n"
"      path: /etc/cni/net.d\n"
"      type: DirectoryOrCreate\n"
"    name: cni-etc\n"
"  - hostPath:\n"
"      path: /run\n"
"      type: Directory\n"
"    name: run\n"
"  - hostPath:\n"
"      path: /var/run/netns\n"
"      type: Directory\n"
"    name: netns\n"
"  - hostPath:\n"
"      path: /etc/\n"
"      type: Directory\n"
"    name: host-etc\n"
;

#endif /* dhcp-cni.h */
